In [1]:
import pandas as pd

In [3]:
df=pd.read_csv("/content/world food production.csv")

In [4]:
df

,Entity,Year,Maize Production (tonnes),Rice Production ( tonnes),Yams Production (tonnes),Wheat Production (tonnes),Tomatoes Production (tonnes),Tea Production ( tonnes ),Sweet potatoes Production (tonnes),Sunflower seed Production (tonnes),...,Oranges Production (tonnes),"Peas, dry Production ( tonnes)",Palm oil Production (tonnes),Grapes Production (tonnes),"Coffee, green Production ( tonnes)",Cocoa beans Production (tonnes),"Meat, chicken Production (tonnes)",Bananas Production ( tonnes),Avocados Production (tonnes),Apples Production (tonnes)
0,Afghanistan,1961,700000.0,319000.00,7.467702e+06,2279000.00,1873812.000,56315.0,3270871.000,12000.000,...,10100.000,232910.000,1131882.00,2.250000e+05,870970.000,835368.000,5600.00,3139079.000,63439.000,15100.000
1,Afghanistan,1962,700000.0,319000.00,7.420515e+06,2279000.00,2044797.000,61519.0,3562524.000,12800.000,...,10100.000,259412.000,1111006.00,2.250000e+05,883512.000,867170.000,6000.00,3181580.000,65118.000,15100.000
2,Afghanistan,1963,713000.0,319000.00,8.479074e+06,1947000.00,2096077.000,63596.0,3409916.000,12800.000,...,10100.000,251529.000,1145004.00,2.250000e+05,996674.000,922621.000,6160.00,3304256.000,61760.000,15100.000
3,Afghanistan,1964,720000.0,380000.00,9.113779e+06,2230000.00,2388264.000,66604.0,3229336.000,12800.000,...,12400.000,247556.000,1160831.00,2.650000e+05,1162048.000,1190061.000,6400.00,3392527.000,62759.000,18400.000
4,Afghanistan,1965,720000.0,380000.00,1.006791e+07,2282000.00,2559608.000,72418.0,3169104.000,13200.000,...,13700.000,266947.000,1138860.00,2.870000e+05,1075084.000,874245.000,6800.00,3450849.000,66269.000,20400.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11907,Zimbabwe,2017,1532572.0,20502618.00,2.673608e+05,30991516.16,324020.864,83904.6,874.408,4077308.066,...,129055.800,40749.600,661978.98,7.018985e+06,63.200,34945.000,75000.00,1267.200,145042.096,1579154.000
11908,Zimbabwe,2018,1560100.0,31871776.60,2.667498e+05,16884482.98,309316.252,66842.6,1383.792,2107639.306,...,168074.000,21606.400,485223.38,3.415107e+06,68.000,34659.800,80357.14,1016.776,143384.384,907419.000
11909,Zimbabwe,2019,773976.0,3382151.40,4.790022e+05,64989733.20,540128.592,9854.4,298831.560,3320915.400,...,1134136.812,45436.400,361128.20,9.645766e+06,30401.400,20961.132,79790.97,195845.198,525095.272,3117813.560
11910,Zimbabwe,2020,1202347.0,3535631.80,7.437612e+05,43020887.20,5635740.200,276279.0,1727311.800,983256.000,...,72179.400,12023.200,279613.40,1.131937e+07,574723.374,158022.122,8000.00,1523258.600,28946.840,7994169.220
11911,Zimbabwe,2021,1469664.0,7575899.96,1.153263e+06,1316724.80,206550.000,145563.0,262706.284,421789.600,...,3597076.600,26225.256,11000.00,3.834786e+05,590070.590,2696.200,8000.00,425303.698,29313.660,112519.364

In [5]:
df1=pd.read_csv("/content/ed_sheeran_spotify.csv")

In [6]:
df1

,Unnamed: 0,name,album,release_date,track_number,id,uri,acousticness,danceability,energy,instrumentalness,liveness,loudness,speechiness,tempo,valence,popularity,duration_ms
0,0,One,x (10th Anniversary Edition),2024-06-21,1,3S3T1bQh67MR424C5urASK,spotify:track:3S3T1bQh67MR424C5urASK,0.8770,0.467,0.321,0.000000,0.0790,-11.121,0.0418,93.417,0.295,44,252760
1,1,I'm a Mess,x (10th Anniversary Edition),2024-06-21,2,4vrQwFJUrcBEOmUrAVf6YL,spotify:track:4vrQwFJUrcBEOmUrAVf6YL,0.5600,0.697,0.379,0.000000,0.0999,-7.755,0.0398,138.757,0.341,43,244573
2,2,Sing,x (10th Anniversary Edition),2024-06-21,3,6dLRhOWgxr1kyL5wO6IE0E,spotify:track:6dLRhOWgxr1kyL5wO6IE0E,0.3000,0.818,0.670,0.000001,0.0601,-4.450,0.0470,119.987,0.947,43,235382
3,3,Don't,x (10th Anniversary Edition),2024-06-21,4,6e3LBgk2dynaAZ96X0ewgK,spotify:track:6e3LBgk2dynaAZ96X0ewgK,0.0113,0.807,0.608,0.000000,0.6350,-7.008,0.0659,95.047,0.849,43,219840
4,4,Nina,x (10th Anniversary Edition),2024-06-21,5,3V4IpWLdFIK3AvZMz9jxKf,spotify:track:3V4IpWLdFIK3AvZMz9jxKf,0.1750,0.791,0.670,0.000000,0.3300,-7.189,0.1470,92.013,0.810,41,225533
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
268,268,Give Me Love,+,2011-09-09,12,0SuG9kyzGRpDqrCWtgD6Lq,spotify:track:0SuG9kyzGRpDqrCWtgD6Lq,0.6940,0.526,0.328,0.000000,0.1120,-9.864,0.0461,116.068,0.110,67,526386
269,269,Autumn Leaves - Deluxe Edition,+,2011-09-09,13,7iBSkXB0pTvZasOLf0Qxk9,spotify:track:7iBSkXB0pTvZasOLf0Qxk9,0.8920,0.555,0.257,0.000001,0.1240,-12.637,0.0299,89.013,0.431,50,200755
270,270,Little Bird - Deluxe Edition,+,2011-09-09,14,4bcgRbGeq4IejesjsiHyTH,spotify:track:4bcgRbGeq4IejesjsiHyTH,0.5650,0.843,0.425,0.000000,0.1020,-8.676,0.0352,104.020,0.284,45,224528
271,271,Gold Rush - Deluxe Edition,+,2011-09-09,15,4mT5mVFaU7trA3UdbGqfB9,spotify:track:4mT5mVFaU7trA3UdbGqfB9,0.7290,0.740,0.248,0.000000,0.1410,-12.659,0.1090,83.786,0.889,44,243162
272,272,Sunburn - Deluxe Edition,+,2011-09-09,16,3YPiRYIUFlcQ0aaLGmeswS,spotify:track:3YPiRYIUFlcQ0aaLGmeswS,0.8650,0.464,0.098,0.000000,0.1010,-12.119,0.0376,78.864,0.234,43,275882

In [7]:
df2=pd.read_csv("/content/bank.csv")

In [8]:
df2

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,deposit
0,59,admin.,married,secondary,no,2343,yes,no,unknown,5,may,1042,1,-1,0,unknown,yes
1,56,admin.,married,secondary,no,45,no,no,unknown,5,may,1467,1,-1,0,unknown,yes
2,41,technician,married,secondary,no,1270,yes,no,unknown,5,may,1389,1,-1,0,unknown,yes
3,55,services,married,secondary,no,2476,yes,no,unknown,5,may,579,1,-1,0,unknown,yes
4,54,admin.,married,tertiary,no,184,no,no,unknown,5,may,673,2,-1,0,unknown,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11157,33,blue-collar,single,primary,no,1,yes,no,cellular,20,apr,257,1,-1,0,unknown,no
11158,39,services,married,secondary,no,733,no,no,unknown,16,jun,83,4,-1,0,unknown,no
11159,32,technician,single,secondary,no,29,no,no,cellular,19,aug,156,2,-1,0,unknown,no
11160,43,technician,married,secondary,no,0,no,yes,cellular,8,may,9,2,172,5,failure,no
11161,34,technician,married,secondary,no,0,no,no,cellular,9,jul,628,1,-1,0,unknown,no

In [10]:
df3=pd.read_csv("/content/train.csv")

In [11]:
df3

,id,chromogram_0_0,chromogram_0_1,chromogram_0_10,chromogram_0_11,chromogram_0_12,chromogram_0_2,chromogram_0_3,chromogram_0_4,chromogram_0_5,...,spec_centr_12,spec_centr_2,spec_centr_3,spec_centr_4,spec_centr_5,spec_centr_6,spec_centr_7,spec_centr_8,spec_centr_9,species
0,0,0.997944,0.832392,0.765386,0.704275,0.655724,0.331064,0.927524,0.307601,0.492226,...,2507.041444,2730.515996,2609.940118,2703.391485,2676.400501,2818.375970,2706.119792,2740.820762,2684.624946,flammea
1,1,0.996255,0.839120,0.760417,0.705142,0.662990,0.329859,0.924461,0.300951,0.493679,...,2490.339399,2730.212864,2609.668564,2703.721292,2676.695013,2818.554958,2705.497472,2741.509333,2683.727859,flammea
2,2,0.970810,0.823540,0.759508,0.709058,0.659750,0.336233,0.933035,0.301501,0.491263,...,2497.486714,2729.438087,2609.010529,2704.515718,2677.465965,2818.971388,2703.952638,2743.213960,2681.482884,flammea
3,3,1.000000,0.855558,0.752038,0.710977,0.664579,0.334564,0.928026,0.292012,0.493557,...,2503.217602,2728.961249,2608.631818,2704.971676,2677.953716,2819.200288,2703.033515,2744.224849,2680.133570,flammea
4,4,1.000000,0.884305,0.741885,0.714775,0.672465,0.329072,0.912804,0.279094,0.501200,...,2523.364512,2728.800252,2608.508516,2705.120155,2678.118949,2819.273155,2702.728487,2744.559785,2679.683390,flammea
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1755,1755,0.005380,0.024429,0.732355,0.356719,0.333551,0.037273,0.002970,0.001497,0.005802,...,1794.271700,2936.033922,3043.898942,3051.139653,3033.832678,2871.200519,2548.170599,2395.403380,1911.572354,vanellus
1756,1756,0.006087,0.023488,0.736068,0.475899,0.558712,0.034946,0.002923,0.001669,0.005330,...,1777.291092,2936.760093,3044.647241,3050.831745,3033.230075,2869.404845,2546.983477,2393.501048,1906.168961,vanellus
1757,1757,0.009701,0.029444,0.732514,0.355017,0.339649,0.036034,0.002836,0.001426,0.007015,...,1716.635360,2937.854159,3045.754084,3050.382522,3032.304073,2866.701211,2545.264742,2390.610397,1898.070621,vanellus
1758,1758,0.005960,0.027000,0.729778,0.407586,0.456757,0.033838,0.002612,0.001531,0.006711,...,1754.841785,2940.428943,3048.254761,3049.440445,3030.047915,2860.345318,2541.460981,2383.669815,1879.307170,vanellus
1759,1759,0.023475,0.027894,0.565448,0.160293,0.120201,0.011314,0.006085,0.005412,0.002588,...,2406.199989,2452.166872,2400.736429,2357.111026,2411.260746,2498.907651,2539.721218,2517.317464,2464.639223,vanellus

In [12]:
df4=pd.read_csv("/content/mobile_os_market_share.csv")

In [13]:
df4

    Year OperatingSystem  Share
0   2009             iOS  59.35
1   2009         Android   5.58
2   2009   BlackBerry OS  14.42
3   2009         Windows   2.91
4   2009       SymbianOS   2.50
..   ...             ...    ...
59  2016         Windows   0.91
60  2016       SymbianOS   0.01
61  2016     Playstation   0.05
62  2016           Other   0.25
63  2016         Unknown   0.21

[64 rows x 3 columns]

In [14]:
df5=pd.read_csv("/content/test.csv")

In [15]:
df5

,id,chromogram_0_0,chromogram_0_1,chromogram_0_10,chromogram_0_11,chromogram_0_12,chromogram_0_2,chromogram_0_3,chromogram_0_4,chromogram_0_5,...,spec_centr_12,spec_centr_2,spec_centr_3,spec_centr_4,spec_centr_5,spec_centr_6,spec_centr_7,spec_centr_8,spec_centr_9,species
0,0,1.000000,0.945011,0.749241,0.714737,0.704973,0.311386,0.881971,0.280575,0.519973,...,2486.230223,2731.690858,2611.073052,2702.003237,2675.278369,2817.586461,2708.632709,2738.029236,2688.206943,flammea
1,1,0.650246,0.590960,0.712450,0.909643,0.727013,0.502476,1.000000,0.242925,0.337245,...,2502.704268,2731.547262,2610.927073,2702.182796,2675.414148,2817.691756,2708.316600,2738.381425,2687.759668,flammea
2,2,1.000000,0.833207,0.770394,0.702116,0.655413,0.326867,0.922793,0.313101,0.493068,...,2503.140943,2731.402739,2610.782378,2702.360640,2675.551167,2817.795126,2708.001038,2738.732677,2687.312293,flammea
3,3,0.991786,0.829836,0.769562,0.702360,0.658253,0.327552,0.923582,0.312167,0.492926,...,2500.947915,2731.257282,2610.638981,2702.536770,2675.689443,2817.896605,2707.686054,2739.083012,2686.864795,flammea
4,4,0.982724,0.826884,0.768729,0.702757,0.662904,0.328242,0.924370,0.311239,0.492785,...,2501.371362,2731.110899,2610.496832,2702.711164,2675.828998,2817.996191,2707.371616,2739.432406,2686.417157,flammea
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4276,4276,0.649796,0.736692,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,2802.481284,2240.286548,2418.287968,2813.681946,3012.511490,2106.426631,2116.934174,3183.595945,2800.894744,europaeus
4277,4277,0.813268,0.842821,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,2822.217214,2240.813117,2418.833052,2814.583207,3011.014394,2105.560280,2118.066143,3185.009332,2799.455579,europaeus
4278,4278,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,2766.211254,2241.337664,2419.379324,2815.483891,3009.504008,2104.697553,2119.203523,3186.412770,2798.018391,europaeus
4279,4279,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,2780.743162,2241.860269,2419.926815,2816.383928,3007.980171,2103.838412,2120.346311,3187.806295,2796.583176,europaeus
4280,4280,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
df6=pd.read_csv("/content/student_performance_data.csv")

In [17]:
df6

,StudentID,Gender,Age,StudyHoursPerWeek,AttendanceRate,GPA,Major,PartTimeJob,ExtraCurricularActivities
0,1,Male,24,37,90.75,3.47,Arts,Yes,No
1,2,Female,22,37,74.90,2.32,Education,No,No
2,3,Male,22,10,53.36,2.38,Business,No,No
3,4,Male,24,10,70.26,3.46,Science,Yes,No
4,5,Male,18,19,74.87,2.31,Education,Yes,No
...,...,...,...,...,...,...,...,...,...
495,496,Male,22,37,76.61,2.97,Science,No,No
496,497,Male,23,11,56.29,3.20,Science,No,No
497,498,Female,20,6,56.64,3.20,Science,No,Yes
498,499,Male,22,18,57.18,2.05,Business,No,Yes
499,500,Female,24,21,96.99,2.64,Engineering,No,No

In [18]:
df7=pd.read_csv("/content/ecommerce_clickstream_transactions.csv")

In [19]:
df7

,UserID,SessionID,Timestamp,EventType,ProductID,Amount,Outcome
0,1,1,2024-07-07 18:00:26.959902,page_view,NaN,NaN,NaN
1,1,1,2024-03-05 22:01:00.072000,page_view,NaN,NaN,NaN
2,1,1,2024-03-23 22:08:10.568453,product_view,prod_8199,NaN,NaN
3,1,1,2024-03-12 00:32:05.495638,add_to_cart,prod_4112,NaN,NaN
4,1,1,2024-02-25 22:43:01.318876,add_to_cart,prod_3354,NaN,NaN
...,...,...,...,...,...,...,...
74812,1000,10,2024-05-11 22:48:45.500117,purchase,prod_1238,186.208225,purchase
74813,1000,10,2024-03-29 04:09:32.514318,logout,NaN,NaN,NaN
74814,1000,10,2024-02-09 02:58:56.128697,login,NaN,NaN,NaN
74815,1000,10,2024-04-30 16:19:48.002633,purchase,prod_2515,198.757849,purchase
74816,1000,10,2024-04-01 02:19:29.148727,logout,NaN,NaN,NaN

In [20]:
df8=pd.read_csv("/content/MA_Public_Schools_2017.csv")

In [21]:
df8

,School Code,School Name,School Type,Function,Contact Name,Address 1,Address 2,Town,State,Zip,...,MCAS_10thGrade_English_Incl. in SGP(#),Accountability and Assistance Level,Accountability and Assistance Description,School Accountability Percentile (1-99),Progress and Performance Index (PPI) - All Students,Progress and Performance Index (PPI) - High Needs Students,District_Accountability and Assistance Level,District_Accountability and Assistance Description,District_Progress and Performance Index (PPI) - All Students,District_Progress and Performance Index (PPI) - High Needs Students
0,10505,Abington High,Public School,Principal,Teresa Sullivan-Cruz,201 Gliniewicz Way,NaN,Abington,MA,2351,...,111.0,Level 1,Meeting gap narrowing goals,42.0,76.0,75.0,Level 3,One or more schools in the district classified...,63.0,60.0
1,10003,Beaver Brook Elementary School,Public School,Principal,Catherine Zinni,1 Ralph Hamlin Lane,NaN,Abington,MA,2351,...,NaN,Level 3,Among lowest performing 20% of subgroups,34.0,69.0,73.0,Level 3,One or more schools in the district classified...,63.0,60.0
2,10002,Center Elementary School,Public School,Principal,Lora Monachino,201 Gliniewicz Way,NaN,Abington,MA,2351,...,NaN,Insufficient data,NaN,NaN,NaN,NaN,Level 3,One or more schools in the district classified...,63.0,60.0
3,10405,Frolio Middle School,Public School,Principal,Matthew MacCurtain,201 Gliniewicz Way,NaN,Abington,MA,2351,...,NaN,Level 2,Not meeting gap narrowing goals,40.0,63.0,64.0,Level 3,One or more schools in the district classified...,63.0,60.0
4,10015,Woodsdale Elementary School,Public School,Principal,Jonathan Hawes,128 Chestnut Street,NaN,Abington,MA,2351,...,NaN,Level 2,Not meeting gap narrowing goals,52.0,65.0,67.0,Level 3,One or more schools in the district classified...,63.0,60.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1856,35060505,Pioneer Charter School of Science II (PCSS-II),Charter School,Principal,Vahit Sevinc,97 Main Street,NaN,Saugus,MA,1906,...,30.0,Insufficient data,NaN,NaN,NaN,NaN,Insufficient data,NaN,NaN,NaN
1857,35100205,Springfield Preparatory Charter School,Charter School,Principal,Bill Spirer,370 Pine St.,NaN,Springfield,MA,1105,...,NaN,Insufficient data,NaN,NaN,NaN,NaN,Insufficient data,NaN,NaN,NaN
1858,39020900,TEC Connections Academy Commonwealth Virtual S...,Public School,Principal,Adam Goldberg,141 Mansion Drive,NaN,East Walpole,MA,2032,...,28.0,Level 3,Very low assessment participation (Less than 90%),NaN,NaN,NaN,Level 3,Very low assessment participation (Less than 90%),NaN,NaN
1859,35050405,UP Academy Charter School of Dorchester,Charter School,Principal,Jabari Peddie,35 Westville Street,NaN,Boston,MA,2124,...,NaN,Level 1,Meeting gap narrowing goals,35.0,92.0,98.0,Level 1,Meeting gap narrowing goals,92.0,98.0
1860,35120305,UP Academy Charter School of Springfield,Charter School,Principal,Scott Given,90 Canal Street Suite 610,NaN,Boston,MA,2114,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
df9=pd.read_csv("/content/Australian Vehicle Prices.csv")

In [23]:
df9

,Brand,Year,Model,Car/Suv,Title,UsedOrNew,Transmission,Engine,DriveType,FuelType,FuelConsumption,Kilometres,ColourExtInt,Location,CylindersinEngine,BodyType,Doors,Seats,Price
0,Ssangyong,2022.0,Rexton,Sutherland Isuzu Ute,2022 Ssangyong Rexton Ultimate (awd),DEMO,Automatic,"4 cyl, 2.2 L",AWD,Diesel,8.7 L / 100 km,5595,White / Black,"Caringbah, NSW",4 cyl,SUV,4 Doors,7 Seats,51990
1,MG,2022.0,MG3,Hatchback,2022 MG MG3 Auto Excite (with Navigation),USED,Automatic,"4 cyl, 1.5 L",Front,Premium,6.7 L / 100 km,16,Black / Black,"Brookvale, NSW",4 cyl,Hatchback,5 Doors,5 Seats,19990
2,BMW,2022.0,430I,Coupe,2022 BMW 430I M Sport,USED,Automatic,"4 cyl, 2 L",Rear,Premium,6.6 L / 100 km,8472,Grey / White,"Sylvania, NSW",4 cyl,Coupe,2 Doors,4 Seats,108988
3,Mercedes-Benz,2011.0,E500,Coupe,2011 Mercedes-Benz E500 Elegance,USED,Automatic,"8 cyl, 5.5 L",Rear,Premium,11 L / 100 km,136517,White / Brown,"Mount Druitt, NSW",8 cyl,Coupe,2 Doors,4 Seats,32990
4,Renault,2022.0,Arkana,SUV,2022 Renault Arkana Intens,USED,Automatic,"4 cyl, 1.3 L",Front,Unleaded,6 L / 100 km,1035,Grey / Black,"Castle Hill, NSW",4 cyl,SUV,4 Doors,5 Seats,34990
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16729,Toyota,2014.0,Alphard,SYC Cars,2014 Toyota Alphard,USED,Automatic,-,Front,Unleaded,-,66000,Grey / -,"Rocklea, QLD",-,Commercial,7 Seats,NaN,29500
16730,Mercedes-Benz,2012.0,S-Class,USED Dealer ad,2012 Mercedes-Benz S-Class CDI BlueTEC,USED,Automatic,-,Rear,Diesel,-,117432,Silver / -,"Port Melbourne, VIC",-,NaN,NaN,NaN,39888
16731,Suzuki,2022.0,Vitara,Bremer Suzuki - New,2022 Suzuki Vitara 1.6L,DEMO,Automatic,"4 cyl, 1.6 L",Front,Unleaded,6.2 L / 100 km,5165,Yellow / -,"Dinmore, QLD",4 cyl,SUV,4 Doors,5 Seats,35280
16732,Mercedes-Benz,2016.0,GLC250,SUV,2016 Mercedes-Benz GLC250,USED,Automatic,"4 cyl, 2 L",AWD,Premium,7.2 L / 100 km,85525,Grey / Black,"Albion, QLD",4 cyl,SUV,4 Doors,5 Seats,41888
16733,Mercedes-Benz,2021.0,C200,Sedan,2021 Mercedes-Benz C200,USED,Automatic,"4 cyl, 2 L",Rear,Unleaded,7 L / 100 km,31852,Gold / -,"Yatala, QLD",4 cyl,Sedan,4 Doors,5 Seats,65888